# Generated by Django 3.1.2 on 2021-11-21 20:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('hash', models.CharField(max_length=128)),
            ],
        ),
    ]
