# Generated by Django 3.1.2 on 2021-12-05 10:15

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                    ),
                ),
                ("hash", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="FilteredLog",
            fields=[
                (
                    "eventlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="index.eventlog",
                    ),
                ),
                ("filter", models.TextField(default="")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filtered_child",
                        to="index.eventlog",
                    ),
                ),
            ],
            bases=("index.eventlog",),
        ),
        migrations.CreateModel(
            name="AttributeFilteredLog",
            fields=[
                (
                    "eventlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="index.eventlog",
                    ),
                ),
                ("filter", models.TextField(default="")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attr_filtered_child",
                        to="index.filteredlog",
                    ),
                ),
            ],
            bases=("index.eventlog",),
        ),
    ]
