# Generated by Django 3.1.2 on 2021-12-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributefilteredlog',
            old_name='filter',
            new_name='cell_filter',
        ),
        migrations.RenameField(
            model_name='attributefilteredlog',
            old_name='parent',
            new_name='column_filtered_log',
        ),
        migrations.RenameField(
            model_name='filteredlog',
            old_name='filter',
            new_name='column_filter',
        ),
        migrations.RenameField(
            model_name='filteredlog',
            old_name='parent',
            new_name='unfiltered_log',
        ),
    ]
