# Generated by Django 3.1.2 on 2021-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_auto_20211122_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="logfiltering",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
