# Generated by Django 3.2.9 on 2021-11-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_auto_20211123_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="filteredlog",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filtered_child",
                to="index.eventlog",
            ),
        ),
        migrations.AlterField(
            model_name="logfiltering",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="AttributeFilteredLog",
            fields=[
                (
                    "eventlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="index.eventlog",
                    ),
                ),
                ("filter", models.TextField(default="")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attr_filtered_child",
                        to="index.filteredlog",
                    ),
                ),
            ],
            bases=("index.eventlog",),
        ),
    ]
