# Generated by Django 3.2.9 on 2021-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_auto_20211125_1825"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogFiltering",
        ),
    ]
